config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 root to: 'pages#home'
 get '/impressum', to: 'pictures#impressum', as: :impressum
 get '/datenschutz', to: 'pictures#datenschutz', as: :datenschutz
 get '/contact', to: 'pictures#contact', as: :contact
 patch 'prints/:id', to: 'prints#update'
 patch 'pictures/:id', to: 'pictures#update'


  resources :pictures, only: [:index, :show, :new, :create, :edit, :destroy]
  resources :prints, only: [:index, :show, :new, :create, :edit, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
has_one_attached :photo
validates :name, presence: true
validates :description, presence: true
end

app/models/print.rb
class Print < ApplicationRecord
has_one_attached :photo
validates :name, presence: true
validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable neu
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    def pundit_user
        current_admin
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 skip_before_action :authenticate_user!, only: :home
  def home
      @pictures = Picture.all
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :impressum, :contact, :show, :datenschutz]

  def index
    @pictures = Picture.all.sort_by{ |picture| picture.id}
  end

  def impressum
  end

  def contact
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.save
      redirect_to pictures_path
    else
      render :new
    end
  end

def update
      @picture = Picture.find(params[:id])
    if
      @picture.update(picture_params)
      redirect_to pictures_path, notice: 'picture was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_path
  end
end

private

def picture_params
  params.require(:picture).permit(:id, :name, :description, :photo)
end

app/controllers/prints_controller.rb
class PrintsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @prints = Print.all.sort_by{ |print| print.id}
  end

  def edit
    @print = Print.find(params[:id])
  end

  def show
    @print = Print.find(params[:id])
  end

  def new
    @print = Print.new
  end

  def create
    @print = Print.new(print_params)
    if @print.save
      redirect_to prints_path
    else
      render :new
    end
  end

  def update
      @print = Print.find(params[:id])
    if
      @print.update(print_params)
      redirect_to prints_path, notice: 'Print was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @print = Print.find(params[:id])
    @print.destroy
    redirect_to prints_path
  end

  private

  def print_params
    params.require(:print).permit(:name, :description, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Lisa Gratzke Artworks</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


</head>

<body>
  <div id="page">
    <div id="page-container">
      <div class="content"><%= yield %></div>
      <%= render 'shared/flashes' %>
    </div>
   <div class="footer-container"> <%= render 'shared/footer' %></div>
  </div>
</body>

</html>

app/views/pages/home.html.erb
<!-- <div class="page-container"> -->
<header class="navbar_index navbar navbar-expand-md navbar-light bg-transparent">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="content_navbar collapse navbar-collapse" id="navbarText">
    <ul class="unorderedlist-nav navbar-nav ml-auto">
      <li class="nav-item"><%= link_to 'IMAGES', pictures_path,  class: 'content-navbar  nav-link' %></li>
      <li class="nav-item"><%= link_to 'PRINTS', prints_path,  class: 'content-navbar  nav-link' %></li>
      <li class="nav-item"><%= link_to 'CONTACT', contact_path,  class: 'content-navbar nav-link' %></li>
      <li class="nav-item"><div class="instagram_icon_div">
        <%= link_to image_tag('instagram.png', alt: "", class: "instagram_icon"), "https://www.instagram.com/lisa_luft/", :target => "_blank"%>
        <%= link_to image_tag('instagram_hover.png', alt: "", class: "instagram_icon"), "https://www.instagram.com/lisa_luft/", :target => "_blank"%></li>
      </div>
    </ul>
  </div>
</header>


 <div id="content_wrap">
  <div class="name_index">
    <h1>LISA GRATZKE</h1>
  </div>
  <div class="image_1 ">
    <%= link_to image_tag('https://res.cloudinary.com/misscarolin/image/upload/v1610985384/image_1_fafwdg.jpg', alt: "", class: "images image1")%>
  </div>
  <div class="image_2">
    <%= link_to image_tag('https://res.cloudinary.com/misscarolin/image/upload/v1610985341/image2_an5tmf.jpg', alt: "", class: "images image2")%>
  </div>
  <div class="image_3">
    <%= link_to image_tag('https://res.cloudinary.com/misscarolin/image/upload/v1611566058/Image3_zdr4yu.jpg', alt: "", class: "images image3")%>
  </div>
  <div class="image_4">
    <%= link_to image_tag('https://res.cloudinary.com/misscarolin/image/upload/v1610985375/image4_zmsjbu.jpg', alt: "", class: "images image4")%>
  </div>
  <div class="image_5">
    <%= link_to image_tag('https://res.cloudinary.com/misscarolin/image/upload/v1610985343/image5_en9j0s.jpg', alt: "", class: "images image5")%>
  </div>
  <div class="image_6">
    <%= link_to image_tag('https://res.cloudinary.com/misscarolin/image/upload/v1610985464/image6_g2cpye.jpg', alt: "", class: "images image6")%>
  </div>
  <div class="image_7">
    <%= link_to image_tag('https://res.cloudinary.com/misscarolin/image/upload/v1610985355/image7_mz65m7.jpg', alt: "", class: "images image7")%>
  </div>
  <div class="image_8">
    <%= link_to image_tag('https://res.cloudinary.com/misscarolin/image/upload/v1610985344/image8_fiophh.jpg', alt: "", class: "images image8")%>
  </div>
  <div class="image_11">
    <%= link_to image_tag('https://res.cloudinary.com/misscarolin/image/upload/v1611566379/image11_rcqply.jpg', alt: "", class: "images image11")%>
  </div>
  <div class="description_index">
    <h2>PERSONAL</h2>
    <h3>ARTWORKS</h3>
  </div>
  <%= link_to "More", pictures_path,  class: "more-button" %>
</div>

<script>
   var button_burger = document.querySelector('button');
   var header = document.querySelector('.name_index')

    button_burger.addEventListener("click", (event) => {
      header.classList.toggle('display-none');
    })
</script>

app/views/pictures/contact.html.erb
 <%= render 'shared/header' %>
    <div class="container_impressum">
        <div class="content_impressum">
            <h1 class="headline-impressum">Contact</h1>
            <div id="lisa-content">
                <p class="lisa-contact-name">Lisa Gratzke</p>
                 <%= link_to image_tag('lisa_contact.png', alt: "lisa-gratzke", class: "lisa-foto")%>
                <p class="lisa-contact-email info">Masterstudium Kunst (M.A. Arts in Education), Osnabrück</p>
                <p class="lisa-contact-email info">Lebt und arbeitet in Berlin</p>
                <p class="lisa-contact">Print Bestellungen und Kontakt via </p>
                <p class="lisa-contact-email">l.gratzke@gmx.de</p>

            </div>
        </div>
    </div>

app/views/pictures/datenschutz.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Datenschutz - Lisa Gratzke</title>
</head>
<body>
    <%= render 'shared/header' %>
    <div class="container_datenschutz">
        <div class="content_impressum">
            <h1 class="headline-datenschutz">Datenschutzerklärung</h1>
            <p class="text-datenschutz">Wir freuen uns sehr über Ihr Interesse an unserem Inhalt. Eine Nutzung der Internetseiten ist grundsätzlich ohne jede Angabe personenbezogener Daten möglich. Im Folgenden unterrichten wir die Besucher*innen unserer Internetseite, über den Umgang mit ihren personenbezogenen Daten. Personenbezogene Daten sind solche Daten, die direkt oder indirekt Rückschlüsse auf Ihre Identität zulassen. Damit erfüllen wir die Informationspflicht nach Art. 13 der Datenschutzgrundverordnung (DSGVO).</p>
            <h5 class="h5-datenschutz">Wir verarbeiten folgende personenbezogene Daten:</h5>
            <p class="text-datenschutz">Informationen, die Ihr Browser automatisch an uns übermittelt, in so genannten Server-Logfiles, darunter Browsertyp/Browserversion, verwendetes Betriebssystem, Referrer-URL, Hostname des zugreifenden Rechners und Uhrzeit der Serveranfrage. Die Rechtsgrundlage hierfür ist Art. 6 Abs. 1 Satz 1 lit. f DSGVO. Unser berechtigtes Interesse an der Datenverarbeitung folgt aus der Gewährleistung eines reibungslosen Verbindungsaufbaus und der komfortablen Nutzung unserer Internetseite sowie aus der Auswertung der Systemsicherung und -stabilität. Die genannten Daten verwenden wir nicht dazu, Rückschlüsse auf Ihre Person zu ziehen.</p>
            <h5 class="h5-datenschutz">Betroffenenrechte</h5>
            <ul>
                <li class="liste-datenschutz">gemäß Art. 15 DSGVO Auskunft über Ihre von uns verarbeiteten personenbezogenen Daten zu verlangen. Insbesondere können Sie Auskunft über die Verarbeitungszwecke, die Kategorie der personenbezogenen Daten, die Kategorien von Empfängern, gegenüber denen Ihre Daten offengelegt wurden oder werden, die geplante Speicherdauer, das Bestehen eines Rechts auf Berichtigung, Löschung, Einschränkung der Verarbeitung oder Widerspruch, das Bestehen eines Beschwerderechts, die Herkunft ihrer Daten, sofern diese nicht bei uns erhoben wurden, sowie über das Bestehen einer automatisierten Entscheidungsfindung einschließlich Profiling und ggf. aussagekräftigen Informationen zu deren Einzelheiten verlangen;</li>
                <li class="liste-datenschutz">gemäß Art. 16 DSGVO unverzüglich die Berichtigung unrichtiger oder Vervollständigung Ihrer bei uns gespeicherten personenbezogenen Daten zu verlangen;</li>
                <li class="liste-datenschutz">gemäß Art. 17 DSGVO die Löschung Ihrer bei uns gespeicherten personenbezogenen Daten zu verlangen, soweit nicht die Verarbeitung zur Ausübung des Rechts auf freie Meinungsäußerung und Information, zur Erfüllung einer rechtlichen Verpflichtung, aus Gründen des öffentlichen Interesses oder zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen erforderlich ist;</li>
                <li class="liste-datenschutz">gemäß Art. 18 DSGVO die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen, soweit die Richtigkeit der Daten von Ihnen bestritten wird, die Verarbeitung unrechtmäßig ist, Sie aber deren Löschung ablehnen und wir die Daten nicht mehr benötigen, Sie jedoch diese zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen benötigen oder Sie gemäß Art. 21 DSGVO Widerspruch gegen die Verarbeitung eingelegt haben;</li>
                <li class="liste-datenschutz">gemäß Art. 20 DSGVO Ihre personenbezogenen Daten, die Sie uns bereitgestellt haben, in einem strukturierten, gängigen und maschinenlesebaren Format zu erhalten oder die Übermittlung an einen anderen Verantwortlichen zu verlangen;</li>
                <li class="liste-datenschutz">gemäß Art. 7 Abs. 3 DSGVO Ihre einmal erteilte Einwilligung jederzeit gegenüber uns zu widerrufen. Dies hat zur Folge, dass wir die Datenverarbeitung, die auf dieser Einwilligung beruhte, für die Zukunft nicht mehr fortführen dürfen und</li>
                <li class="liste-datenschutz">gemäß Art. 77 DSGVO sich bei einer Aufsichtsbehörde zu beschweren. In der Regel können Sie sich hierfür an die Aufsichtsbehörde Ihres üblichen Aufenthaltsortes oder Arbeitsplatzes wenden.</li>
                <li class="liste-datenschutz">Zur Wahrnehmung Ihrer Betroffenenrechte kontaktieren Sie uns bitte per E-Mail an l.gratzke@gmx.de</li>
            </ul>
            <h5 class="h5-datenschutz">Weitergabe an Dritte</h5>
            <p class="text-datenschutz">Wir übermitteln übermittelt keine Daten außerhalb des Anwendungsbereichs der Datenschutzgrundverordnung (DSGVO) sofern keine gesetzliche Pflicht zur Weitergabe besteht oder die Weitergabe der Strafverfolgung dient.</p>
            <h5 class="h5-datenschutz">Cookies</h5>
            <p class="text-datenschutz">Die Internetseiten verwenden teilweise sogenannte Cookies. Cookies sind kleine Textdateien, die auf Ihrem Rechner abgelegt werden und die Ihr Browser speichert. Cookies richten auf Ihrem Rechner keinen Schaden an und enthalten keine Viren. Cookies dienen dazu, unser Angebot nutzerfreundlicher, effektiver und sicherer zu machen.<br><br>Die von uns verwendeten Cookies sind so genannte „Session-Cookies“. Sie werden nach Ende Ihres Besuchs unseres Internetangebots automatisch gelöscht. Die Verarbeitung erfolgt gemäß Art. 6 Abs. 1 lit. f DSGVO auf Basis unseres berechtigten Interesses an einer nutzerfreundlichen Gestaltung unserer Website<br><br>Sie können Ihren Browser so einstellen, dass Sie über das Setzen von Cookies informiert werden und Cookies nur im Einzelfall erlauben, die Annahme von Cookies für bestimmte Fälle oder generell ausschließen sowie das automatische Löschen der Cookies beim Schließen des Browsers aktivieren. Bei der Deaktivierung von Cookies kann die Funktionalität von Internetseiten eingeschränkt sein.</p>
            <h5 class="h5-datenschutz">Externe Links</h5>
            <p class="text-datenschutz">Diese Website enthält Verknüpfungen zu Websites Dritter ("externe Links"). Diese Websites unterliegen der Haftung der jeweiligen Betreiber. Der Anbieter hat bei der erstmaligen Verknüpfung der externen Links die fremden Inhalte daraufhin überprüft, ob etwaige Rechtsverstöße bestehen. Zu dem Zeitpunkt waren keine Rechtsverstöße ersichtlich. Der Anbieter hat keinerlei Einfluss auf die aktuelle und zukünftige Gestaltung und auf die Inhalte der verknüpften Seiten. Das Setzen von externen Links bedeutet nicht, dass sich der Anbieter die hinter dem Verweis oder Link liegenden Inhalte zu Eigen macht. Eine ständige Kontrolle der externen Links ist für den Anbieter ohne konkrete Hinweise auf Rechtsverstöße nicht zumutbar. Bei Kenntnis von Rechtsverstößen werden jedoch derartige externe Links unverzüglich gelöscht.</p>
            <h5 class="h5-datenschutz">Urheber- und Leistungsschutzrechte</h5>
            <p class="text-datenschutz">Die auf dieser Website veröffentlichten Inhalte unterliegen dem deutschen Urheber- und Leistungsschutzrecht. Jede vom deutschen Urheber- und Leistungsschutzrecht nicht zugelassene Verwertung bedarf der vorherigen schriftlichen Zustimmung des Anbieters oder jeweiligen Rechteinhabers. Dies gilt insbesondere für Vervielfältigung, Bearbeitung, Übersetzung, Einspeicherung, Verarbeitung bzw. Wiedergabe von Inhalten in Datenbanken oder anderen elektronischen Medien und Systemen. Inhalte und Rechte Dritter sind dabei als solche gekennzeichnet. Die unerlaubte Vervielfältigung oder Weitergabe einzelner Inhalte oder kompletter Seiten ist nicht gestattet und strafbar. Lediglich die Herstellung von Kopien und Downloads für den persönlichen, privaten und nicht kommerziellen Gebrauch ist erlaubt.</p>
            <h5 class="h5-datenschutz">Kontakt</h5>
            <p class="text-datenschutz">Wenn Sie allgemeine Fragen zu den Diensten oder den von uns über Sie erfassten Daten und deren Verwendung haben, kontaktieren Sie uns bitte unter: <br><br>Lisa Gratzke<br>l.gratzke@gmx.de</p>
            <h5 class="h5-datenschutz">Änderungen an dieser Datenschutzerklärung</h5>
            <p class="text-datenschutz">Wir behalten uns das Recht vor, diese Datenschutzerklärung jederzeit mit Wirkung für die Zukunft zu ändern. Eine jeweils aktuelle Version ist an dieser Stelle verfügbar. Bitte suchen Sie die Website regelmäßig auf und informieren sich über die geltende Datenschutzerklärung.<br><br>Stand 02/2021</p>
        </div>
    </div>

</body>
</html>

app/views/pictures/edit.html.erb
 <%= render 'shared/header' %>

<div class="new-container">
    <div class="container">
        <div class="column">
            <div class="row justify-content-center">
            <div class="col-6">
                <h1>Edit Image</h1>
                <%= render 'shared/form'%>
            </div>
            </div>
        </div>
    </div>
</div>

app/views/pictures/impressum.html.erb
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Impressum - Lisa Gratzke</title>
</head>
<body>
 <%= render 'shared/header' %>
    <div class="container_impressum">
        <div class="content_impressum">
            <h1 class="headline-impressum">Impressum</h1>
            <div id="lisa-content">
                <p class="header-p">Verantwortlich für den <br> Seiteninhalt nach §55 II RStV</p>
                <p>Lisa Gratzke</p>
                <p>l.gratzke@gmx.de</p>
            </div>
             <div id="caro-content">
                <p class="header-p">Webdesign</p>
                <%= link_to "Carolin Wagner", "https://www.linkedin.com/in/carolin-wagner-333364a3/", id: "caro-link" %>
            </div>
        </div>
    </div>
</body>
</html>

app/views/pictures/index.html.erb
 <%= render 'shared/header' %>

<div class="flexbox">
  <div class="container-fluid">
    <div class="row sortable-pictures align-items-center">
      <% @pictures.each do |picture| %>
        <div class="col-xs-12 col-sm-6 col-lg-4 card-content">
          <%= render 'shared/card',picture: picture %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% if current_user.nil? == false %>
<script>

  // $(".sortable-pictures").sortable({});
</script>
<% end %>

app/views/pictures/new.html.erb
 <%= render 'shared/header' %>

<div class="new-container">
    <div class="container">
        <div class="column">
            <div class="row justify-content-center">
            <div class="col-6">
                <h1>New Image</h1>
                <%= render 'shared/form'%>
            </div>
            </div>
        </div>
    </div>
</div>

app/views/pictures/show.html.erb
 <%= render 'shared/header' %>
    <div class="container-show">
        <div class="content-show">
            <%= cl_image_tag(@picture.photo.key, crop: :fill, width: 500, class:"image-show") %>
            <div class="show-name-description">
                <h1 class="headline-show"><%= @picture.name %></h1>
                <p class="image-pictures-description"><%= @picture.description %></p>
            </div>
        </div>
    </div>

app/views/prints/edit.html.erb
  <%= render 'shared/header' %>

<div class="new-container">
    <div class="container">
        <div class="column">
            <div class="row justify-content-center">
            <div class="col-6">
                <h1>Edit Print</h1>
                <%= simple_form_for(@print) do |f| %>

                <%= f.input :name %>
                <%= f.input :description %>
                <%= f.input :photo, as: :file, class: "btn btn-outline-secondary" %>
                <%= f.button :submit, class: "btn btn-secondary" %>
                <% end %>
            </div>
            </div>
        </div>
    </div>
</div>

app/views/prints/index.html.erb
 <%= render 'shared/header' %>


<div class="flexbox">
  <div class="container-fluid">
    <div class="row align-items-center">
        <div class="col-12 text-center">
      <% @prints.each do |print| %>

<!-- Start of Print Card -->
        <% if current_user.nil? == false %>
          <%= link_to print_path(print), class: "picture_link" do %>
           <div class="flexbox-edit-delete">
              <p class="bin"><%= link_to image_tag('bin2.png', class: "delete_picture_card"), print_path(print.id), method: :delete, data: {confirm: 'are you sure?'}, class: "delete_pictures_link" %><p>
              <p class="bin"><%= link_to image_tag('pen.png', class: "delete_picture_card"), edit_print_path(print.id) %><p>
           </div>
          <% end %>
        <% end %>

        <div class="cards print">
             <%= link_to print_path(print), class: "picture_link" do %>
            <%= cl_image_tag(print.photo.key, crop: :fill) %>
            <div class="card-category">
                <div class="content-text">
                    <h2 class="card-headline"><%= print.name %></h2>
                    <p class ="description-card-text"><%= print.description %></p>
                </div>
            </div>
        </div>
        <% end %>
        <% end %>

<!-- End of Print Card -->
        </div>
    </div>
  </div>
</div>

<% if current_user.nil? == false %>
<script>
  $(".text-center").sortable({});
</script>
<% end %>

app/views/prints/new.html.erb
 <%= render 'shared/header' %>

<div class="new-container">
    <div class="container">
        <div class="column">
            <div class="row justify-content-center">
            <div class="col-6">
                <h1>New Print</h1>
                <%= simple_form_for(@print) do |f| %>
                <%= f.input :name %>
                <%= f.input :description %>
                <%= f.input :photo, as: :file, class: "btn btn-outline-secondary" %>
                <%= f.button :submit, class: "btn btn-secondary" %>
                <% end %>
            </div>
            </div>
        </div>
    </div>
</div>

app/views/prints/show.html.erb
 <%= render 'shared/header' %>
      <div class="container-show">
        <div class="content-show">
            <%= cl_image_tag(@print.photo.key, crop: :fill, width: 500, class:"image-show") %>
            <div class="show-name-description">
                <h1 class="headline-show"><%= @print.name %></h1>
                <p class="image-pictures-description"><%= @print.description %></p>
            </div>
        </div>
    </div>

app/views/shared/_card.html.erb
    <% if current_user.nil? == false %>
     <div class="flexbox-edit-delete">
        <p class="bin"><%= link_to image_tag('bin2.png', class: "delete_picture_card"), picture_path(picture.id), method: :delete, data: {confirm: 'are you sure?'}, class: "delete_pictures_link" %><p>
        <p class="bin"><%= link_to image_tag('pen.png', class: "delete_picture_card"), edit_picture_path(picture.id) %><p>
    </div>
    <% end %>
<div class="cards">
    <%= link_to picture_path(picture), class: "picture_link" do %>
    <%= cl_image_tag(picture.photo.key, crop: :fill, width: 400) %>
    <div class="card-category">
        <div class="content-text">
            <h2 class="card-headline"><%= picture.name %></h2>
            <p class ="description-card-text"><%= picture.description %></p>
        </div>
    </div>
</div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer_links">
  <% if current_user.nil?%>
    <%= link_to "LOGIN", new_user_session_path, class: "footer_link"%>
  <% end %>
  <% if current_user.nil? == false %>
    <%= link_to 'NEW IMAGE', new_picture_path,  class: 'footer_link' %>
    <%= link_to 'NEW PRINT', new_print_path,  class: 'footer_link' %>
    <%= link_to "LOGOUT", destroy_user_session_path, class: "footer_link", :method => :delete %>
  <% end %>
    <%= link_to 'IMPRESSUM', impressum_path,  class: 'footer_link' %>
    <%= link_to 'DATENSCHUTZ', datenschutz_path,  class: 'footer_link' %>
  </div>
  <div class="copyright_section">
    <%= image_tag('copyright.png', alt: "copyright", id: "copyright")%>
    <p class="footer_name">Lisa Gratzke 2021</p>
  </div>
</footer>

app/views/shared/_form.html.erb
        <%= simple_form_for(@picture) do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :photo, as: :file, class: "btn btn-outline-secondary" %>
          <%= f.button :submit, class: "btn btn-secondary" %>
        <% end %>

app/views/shared/_header.html.erb
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">


<header class="navbar_index navbar navbar-expand-md navbar-light bg-transparent">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="content_navbar collapse navbar-collapse" id="navbarText">
    <ul class="unorderedlist-nav navbar-nav ml-auto">
      <li class="nav-item"><%= link_to "HOME", root_path, class: 'content-navbar nav-link' %></li>
      <li class="nav-item"><%= link_to 'IMAGES', pictures_path,  class: 'content-navbar  nav-link' %></li>
      <li class="nav-item"><%= link_to 'PRINTS', prints_path,  class: 'content-navbar  nav-link' %></li>
      <li class="nav-item"><%= link_to 'CONTACT', contact_path,  class: 'content-navbar nav-link' %></li>
      <li class="nav-item"><div class="instagram_icon_div">
        <%= link_to image_tag('instagram.png', alt: "", class: "instagram_icon"), "https://www.instagram.com/lisa_luft/", :target => "_blank"%>
        <%= link_to image_tag('instagram_hover.png', alt: "", class: "instagram_icon"), "https://www.instagram.com/lisa_luft/", :target => "_blank"%></li>
      </div>
    </ul>
  </div>
</header>